# Generated by Django 5.1 on 2024-08-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hot_item',
            field=models.BooleanField(default=False),
        ),
    ]
