# Generated by Django 5.1 on 2024-08-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('content', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='core_images')),
            ],
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='core_images'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(),
        ),
    ]
