# Generated by Django 5.1 on 2024-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news_alter_carousel_image_alter_carousel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storeimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='core_images')),
                ('the_big', models.BooleanField(default=False)),
            ],
        ),
    ]
