# Generated by Django 5.1 on 2024-08-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
